#!/usr/bin/env node

import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { basename, extname, join, relative } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
  POSTS_DIR,
  PAGES_DIR,
  ROOT_DIR,
  TYPE_TOOLCHAIN_DIR,
} from "./build/constants.mjs";
import { normalizePosixPath, resolveSafeBuildSubdir, walkFiles } from "./build/helpers.mjs";
import { dedupeCodepoints, splitBasicAndSiteText } from "./font-subset.mjs";
import { createProjectTempDir } from "./tmp-dir.mjs";

const DEFAULT_CACHE_ROOT = ".typ-blog-cache";
const FONT_SOURCE_DIR = join(ROOT_DIR, "fonts-src");
const FONT_CACHE_VERSION = 1;
const FONT_GENERATOR_VERSION = "font-artifacts-v1";
const FONT_BUILD_MODES = new Set(["auto", "dev", "release"]);
const ALLOWED_TEXT_EXTENSIONS = new Set([".typ", ".md", ".txt"]);
const BASIC_ASCII_TEXT = dedupeCodepoints(
  Array.from({ length: 95 }, (_, index) => String.fromCodePoint(0x20 + index)).join("")
  + "\n\r\t",
);
const BASIC_UNICODE_RANGE = "U+0009-000D, U+0020-007E";
const SITE_CJK_UNICODE_RANGE = "U+3000-303F, U+3400-4DBF, U+4E00-9FFF, U+FF00-FFEF";
const FONT_CSS_OUTPUT_REL = "fonts.css";
const FONT_FILES_DIRNAME = "fonts";
const POEM_FONT_FAMILY_NAME = "Site Poem";

function formatDurationMs(durationMs) {
  if (durationMs < 1000) {
    return `${Math.round(durationMs)}ms`;
  }

  return `${(durationMs / 1000).toFixed(2)}s`;
}

const FONT_SPECS = [
  {
    familyName: "Site Noto Sans",
    slug: "noto-sans-sc",
    source: {
      400: join(FONT_SOURCE_DIR, "NotoSansCJKsc-Regular.otf"),
      700: join(FONT_SOURCE_DIR, "NotoSansCJKsc-Bold.otf"),
    },
  },
  {
    familyName: "Site Noto Serif",
    slug: "noto-serif-sc",
    source: {
      400: join(FONT_SOURCE_DIR, "NotoSerifCJKsc-Regular.otf"),
      700: join(FONT_SOURCE_DIR, "NotoSerifCJKsc-Bold.otf"),
    },
  },
  {
    familyName: "Site Noto Mono",
    slug: "noto-mono-sc",
    source: {
      400: join(FONT_SOURCE_DIR, "NotoSansMonoCJKsc-Regular.otf"),
      700: join(FONT_SOURCE_DIR, "NotoSansMonoCJKsc-Bold.otf"),
    },
  },
  {
    familyName: "Site Kai",
    slug: "site-kai",
    source: {
      400: join(FONT_SOURCE_DIR, "Kaiti.ttf"),
    },
  },
];

const STATIC_TEXT_SOURCES = [
  join(ROOT_DIR, "config.typ"),
  POSTS_DIR,
  PAGES_DIR,
  TYPE_TOOLCHAIN_DIR,
  join(ROOT_DIR, "site.config.json"),
];

export function getFontArtifactPaths(cacheRootPath) {
  const artifactRoot = join(cacheRootPath, "artifacts", "fonts");
  return {
    artifactRoot,
    outputDir: join(artifactRoot, FONT_FILES_DIRNAME),
    cssPath: join(artifactRoot, FONT_CSS_OUTPUT_REL),
    manifestPath: join(artifactRoot, "manifest.json"),
  };
}

export function resolveFontBuildMode(requestedMode = "auto", env = process.env) {
  if (!FONT_BUILD_MODES.has(requestedMode)) {
    throw new Error(`Unsupported font build mode: ${requestedMode}`);
  }

  if (requestedMode === "auto") {
    return env.CI ? "release" : "dev";
  }

  return requestedMode;
}

function inferFontFormat(sourcePath) {
  const extension = extname(sourcePath).toLowerCase();
  if (extension === ".otf") {
    return "opentype";
  }

  if (extension === ".ttf") {
    return "truetype";
  }

  return "unknown";
}

export function getDevelopmentFontAssetDescriptors() {
  const descriptors = [];

  for (const spec of FONT_SPECS) {
    for (const [weight, sourcePath] of Object.entries(spec.source)) {
      descriptors.push({
        familyName: spec.familyName,
        slug: spec.slug,
        weight: Number(weight),
        sourcePath,
        fileName: basename(sourcePath),
        format: inferFontFormat(sourcePath),
      });
    }
  }

  descriptors.sort((a, b) => a.fileName.localeCompare(b.fileName));
  return descriptors;
}

export function buildDevelopmentFontCssText() {
  const lines = [
    "/* Generated by development font builder. */",
    "",
  ];

  for (const descriptor of getDevelopmentFontAssetDescriptors()) {
    lines.push("@font-face {");
    lines.push(`  font-family: \"${descriptor.familyName}\";`);
    lines.push(`  src: url(\"/assets/fonts/${descriptor.fileName}\") format(\"${descriptor.format}\");`);
    lines.push("  font-style: normal;");
    lines.push(`  font-weight: ${descriptor.weight};`);
    lines.push("  font-display: swap;");
    lines.push("}");
    lines.push("");
  }

  appendPoemFontAliasCss(lines, {
    basicSrc: `url("/assets/fonts/NotoSerifCJKsc-Regular.otf") format("opentype")`,
    basicBoldSrc: `url("/assets/fonts/NotoSerifCJKsc-Bold.otf") format("opentype")`,
    cjkSrc: `local("KaiTi"), local("Kaiti SC"), local("STKaiti"), local("Kai"), local("LXGW WenKai"), url("/assets/fonts/Kaiti.ttf") format("truetype")`,
  });

  return `${lines.join("\n").trim()}\n`;
}

function appendPoemFontAliasCss(lines, { basicSrc, basicBoldSrc, cjkSrc }) {
  const poemWeights = [
    { weight: 400, serifSrc: basicSrc },
    { weight: 700, serifSrc: basicBoldSrc },
  ];

  for (const entry of poemWeights) {
    lines.push("@font-face {");
    lines.push(`  font-family: "${POEM_FONT_FAMILY_NAME}";`);
    lines.push(`  src: ${entry.serifSrc};`);
    lines.push("  font-style: normal;");
    lines.push(`  font-weight: ${entry.weight};`);
    lines.push("  font-display: swap;");
    lines.push(`  unicode-range: ${BASIC_UNICODE_RANGE};`);
    lines.push("}");
    lines.push("");
  }

  for (const weight of [400, 700]) {
    lines.push("@font-face {");
    lines.push(`  font-family: "${POEM_FONT_FAMILY_NAME}";`);
    lines.push(`  src: ${cjkSrc};`);
    lines.push("  font-style: normal;");
    lines.push(`  font-weight: ${weight};`);
    lines.push("  font-display: swap;");
    lines.push(`  unicode-range: ${SITE_CJK_UNICODE_RANGE};`);
    lines.push("}");
    lines.push("");
  }
}

export function findMissingCommands(commandNames, commandExists = defaultCommandExists) {
  return commandNames.filter((commandName) => !commandExists(commandName));
}

export function resolvePyftsubsetCommand(commandExists = defaultCommandExists) {
  if (commandExists("pyftsubset")) {
    return ["pyftsubset"];
  }

  if (commandExists("python3-fonttools-subset")) {
    return ["python3", "-m", "fontTools.subset"];
  }

  return null;
}

export function computeContentHash(value) {
  const hash = createHash("sha256");
  if (Buffer.isBuffer(value)) {
    hash.update(value);
  } else {
    hash.update(String(value), "utf8");
  }
  return hash.digest("hex");
}

export function computeFontArtifactFingerprint({ slug, weight, suffix, sourceHash, textHash }) {
  return computeContentHash([
    FONT_CACHE_VERSION,
    FONT_GENERATOR_VERSION,
    slug,
    String(weight),
    suffix,
    sourceHash,
    textHash,
  ].join("\0"));
}

export function planFontArtifactBuild({
  subsetDescriptors,
  previousManifest = null,
  artifactExists = () => false,
  reuseCache = true,
  sourceFingerprints = [],
  corpusHashes = {},
  cssText,
  existingCssFingerprint = null,
}) {
  const previousFiles = previousManifest?.files || {};
  const previousCss = previousManifest?.css || null;
  const subsetPlans = subsetDescriptors.map((descriptor) => {
    const previous = previousFiles[descriptor.outputRelPath];
    const shouldBuild = !reuseCache
      || previous == null
      || previous.fingerprint !== descriptor.fingerprint
      || !artifactExists(descriptor.outputRelPath);

    return {
      ...descriptor,
      shouldBuild,
    };
  });

  const cssFingerprint = computeContentHash(cssText);
  const shouldWriteCss = !reuseCache
    || previousCss == null
    || previousCss.fingerprint !== cssFingerprint
    || existingCssFingerprint !== cssFingerprint
    || !artifactExists(FONT_CSS_OUTPUT_REL);

  const manifest = {
    version: FONT_CACHE_VERSION,
    generatorVersion: FONT_GENERATOR_VERSION,
    generatedAt: new Date().toISOString(),
    corpusHashes,
    sources: Object.fromEntries(sourceFingerprints.map((fingerprint) => [
      fingerprint.path,
      fingerprint,
    ])),
    files: Object.fromEntries(subsetPlans.map((plan) => [
      plan.outputRelPath,
      {
        fingerprint: plan.fingerprint,
        familyName: plan.familyName,
        slug: plan.slug,
        weight: plan.weight,
        suffix: plan.suffix,
        sourcePath: plan.sourceRelPath,
        sourceHash: plan.sourceHash,
        textHash: plan.textHash,
      },
    ])),
    css: {
      file: FONT_CSS_OUTPUT_REL,
      fingerprint: cssFingerprint,
    },
  };

  const rebuiltSubsetCount = subsetPlans.filter((plan) => plan.shouldBuild).length;
  const totalSubsetCount = subsetPlans.length;
  const status = rebuiltSubsetCount === 0 && !shouldWriteCss
    ? "cache-hit"
    : rebuiltSubsetCount === totalSubsetCount && shouldWriteCss
      ? "rebuilt"
      : "partially-rebuilt";

  return {
    subsetPlans,
    cssPlan: {
      outputRelPath: FONT_CSS_OUTPUT_REL,
      fingerprint: cssFingerprint,
      text: cssText,
      shouldWrite: shouldWriteCss,
    },
    manifest,
    rebuiltSubsetCount,
    totalSubsetCount,
    status,
  };
}

function defaultCommandExists(commandName) {
  if (commandName === "python3-fonttools-subset") {
    const result = spawnSync("python3", ["-m", "fontTools.subset", "--help"], {
      cwd: ROOT_DIR,
      encoding: "utf8",
    });
    return result.status === 0;
  }

  const result = spawnSync("bash", ["-lc", `command -v ${commandName}`], {
    cwd: ROOT_DIR,
    encoding: "utf8",
  });
  return result.status === 0;
}

function readSourceText(sourcePath) {
  const extension = extname(sourcePath).toLowerCase();
  if (ALLOWED_TEXT_EXTENSIONS.has(extension) || basename(sourcePath) === "site.config.json") {
    return readFileSync(sourcePath, "utf8");
  }

  const files = walkFiles(
    sourcePath,
    (filePath) => ALLOWED_TEXT_EXTENSIONS.has(extname(filePath).toLowerCase()),
  );

  return files.map((filePath) => readFileSync(filePath, "utf8")).join("\n");
}

function collectCorpusText() {
  const chunks = [
    "Groove Blog 标签 日期 分类 上一篇 下一篇 目录 关于 文章 诗歌 Typst HTML CSS JavaScript 你好世界",
  ];

  for (const sourcePath of STATIC_TEXT_SOURCES) {
    if (!existsSync(sourcePath)) continue;
    chunks.push(readSourceText(sourcePath));
  }

  return chunks.join("\n");
}

function collectPoemCorpusText() {
  const poemRoot = join(POSTS_DIR, "poems");
  if (!existsSync(poemRoot)) {
    return "";
  }

  return readSourceText(poemRoot);
}

function ensureSourcesExist() {
  const missing = [];

  for (const spec of FONT_SPECS) {
    for (const sourcePath of Object.values(spec.source)) {
      if (!existsSync(sourcePath)) {
        missing.push(sourcePath);
      }
    }
  }

  if (missing.length > 0) {
    throw new Error(`Missing font sources:\n- ${missing.join("\n- ")}`);
  }
}

function ensureBuildToolsExist() {
  const missing = [];
  if (resolvePyftsubsetCommand() == null) {
    missing.push("pyftsubset or python3 -m fontTools.subset");
  }
  missing.push(...findMissingCommands(["woff2_compress"]));

  if (missing.length > 0) {
    throw new Error(
      `Missing font build tools:\n- ${missing.join("\n- ")}\nInstall the required dependencies before running npm run fonts:build.`,
    );
  }
}

function makeSourceFingerprint(sourcePath) {
  const stats = statSync(sourcePath);
  return {
    path: normalizePosixPath(relative(ROOT_DIR, sourcePath)),
    size: stats.size,
    mtimeMs: stats.mtimeMs,
    hash: computeContentHash(readFileSync(sourcePath)),
  };
}

function collectSourceFingerprints() {
  const fingerprints = [];

  for (const spec of FONT_SPECS) {
    for (const sourcePath of Object.values(spec.source)) {
      fingerprints.push(makeSourceFingerprint(sourcePath));
    }
  }

  fingerprints.sort((a, b) => a.path.localeCompare(b.path));
  return fingerprints;
}

function buildSubsetDescriptors(sourceFingerprints, siteCorpusText, poemCorpusText) {
  const sourceByPath = new Map(sourceFingerprints.map((fingerprint) => [join(ROOT_DIR, fingerprint.path), fingerprint]));
  const { basicText, siteText } = splitBasicAndSiteText(siteCorpusText);
  const { basicText: poemBasicText, siteText: poemSiteText } = splitBasicAndSiteText(poemCorpusText);
  const descriptors = [];

  for (const spec of FONT_SPECS) {
    for (const [weight, sourcePath] of Object.entries(spec.source)) {
      const sourceFingerprint = sourceByPath.get(sourcePath);
      const subsetInputs = spec.slug === "site-kai"
        ? [
          { suffix: "basic", text: BASIC_ASCII_TEXT + poemBasicText },
          { suffix: "site-cjk", text: poemSiteText },
        ]
        : [
          { suffix: "basic", text: BASIC_ASCII_TEXT + basicText },
          { suffix: "site-cjk", text: siteText },
        ];

      for (const subset of subsetInputs) {
        const textValue = dedupeCodepoints(subset.text);
        const textHash = computeContentHash(textValue);
        const outputFileName = `${spec.slug}-${subset.suffix}-${weight}.woff2`;
        const outputRelPath = normalizePosixPath(`${FONT_FILES_DIRNAME}/${outputFileName}`);
        descriptors.push({
          familyName: spec.familyName,
          slug: spec.slug,
          weight: Number(weight),
          suffix: subset.suffix,
          sourcePath,
          sourceRelPath: sourceFingerprint.path,
          sourceHash: sourceFingerprint.hash,
          textValue,
          textHash,
          outputFileName,
          outputRelPath,
          fingerprint: computeFontArtifactFingerprint({
            slug: spec.slug,
            weight,
            suffix: subset.suffix,
            sourceHash: sourceFingerprint.hash,
            textHash,
          }),
        });
      }
    }
  }

  return descriptors;
}

function buildFontCssText() {
  const lines = [
    "/* Generated by font artifact builder. */",
    "",
  ];

  for (const spec of FONT_SPECS) {
    for (const weight of Object.keys(spec.source)) {
      const subsets = [
        { suffix: "basic", unicodeRange: BASIC_UNICODE_RANGE },
        { suffix: "site-cjk", unicodeRange: SITE_CJK_UNICODE_RANGE },
      ];

      for (const subset of subsets) {
        const fileName = `${spec.slug}-${subset.suffix}-${weight}.woff2`;
        lines.push("@font-face {");
        lines.push(`  font-family: \"${spec.familyName}\";`);
        lines.push(`  src: url(\"/assets/fonts/${fileName}\") format(\"woff2\");`);
        lines.push("  font-style: normal;");
        lines.push(`  font-weight: ${weight};`);
        lines.push("  font-display: swap;");
        lines.push(`  unicode-range: ${subset.unicodeRange};`);
        lines.push("}");
        lines.push("");
      }
    }
  }

  appendPoemFontAliasCss(lines, {
    basicSrc: `url("/assets/fonts/noto-serif-sc-basic-400.woff2") format("woff2")`,
    basicBoldSrc: `url("/assets/fonts/noto-serif-sc-basic-700.woff2") format("woff2")`,
    cjkSrc: `local("KaiTi"), local("Kaiti SC"), local("STKaiti"), local("Kai"), local("LXGW WenKai"), url("/assets/fonts/site-kai-site-cjk-400.woff2") format("woff2")`,
  });

  return `${lines.join("\n").trim()}\n`;
}

function loadPreviousManifest(manifestPath) {
  if (!existsSync(manifestPath)) {
    return null;
  }

  try {
    const parsed = JSON.parse(readFileSync(manifestPath, "utf8"));
    if (parsed.version !== FONT_CACHE_VERSION || parsed.generatorVersion !== FONT_GENERATOR_VERSION) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

function runPyftsubset(sourcePath, outputPath, textValue, tempDir) {
  const subsetCommand = resolvePyftsubsetCommand();
  if (subsetCommand == null) {
    throw new Error("No available font subset command found.");
  }

  const textFilePath = join(tempDir, `${basename(outputPath, ".woff2")}.txt`);
  writeFileSync(textFilePath, textValue, "utf8");

  const subsetTempPath = `${outputPath}.subset${extname(sourcePath)}`;
  const result = spawnSync(
    subsetCommand[0],
    [
      ...subsetCommand.slice(1),
      sourcePath,
      `--output-file=${subsetTempPath}`,
      `--text-file=${textFilePath}`,
      "--layout-features=*",
      "--passthrough-tables",
      "--ignore-missing-glyphs",
      "--ignore-missing-unicodes",
      "--name-IDs=*",
      "--name-legacy",
      "--name-languages=*",
      "--glyph-names",
      "--symbol-cmap",
      "--legacy-cmap",
      "--notdef-glyph",
      "--notdef-outline",
    ],
    {
      cwd: ROOT_DIR,
      encoding: "utf8",
    },
  );

  if (result.status !== 0) {
    throw new Error(
      `${subsetCommand.join(" ")} failed for ${sourcePath}\n${(result.stderr || result.stdout || "").trim()}`,
    );
  }

  const compressResult = spawnSync("woff2_compress", [subsetTempPath], {
    cwd: ROOT_DIR,
    encoding: "utf8",
  });

  if (compressResult.status !== 0) {
    throw new Error(
      `woff2_compress failed for ${subsetTempPath}\n${(compressResult.stderr || compressResult.stdout || "").trim()}`,
    );
  }

  const compressedPath = subsetTempPath.replace(/\.(otf|ttf)$/i, ".woff2");
  renameSync(compressedPath, outputPath);
  rmSync(subsetTempPath, { force: true });
}

function removeStaleSubsetFiles(outputDir, retainedOutputRelPaths) {
  if (!existsSync(outputDir)) {
    return;
  }

  const retained = new Set(retainedOutputRelPaths.map((relPath) => basename(relPath)));
  const currentFiles = walkFiles(outputDir).filter((filePath) => extname(filePath).toLowerCase() === ".woff2");

  for (const filePath of currentFiles) {
    if (!retained.has(basename(filePath))) {
      rmSync(filePath, { force: true });
    }
  }
}

function syncFontArtifacts(buildPlan, artifactPaths) {
  mkdirSync(artifactPaths.artifactRoot, { recursive: true });
  mkdirSync(artifactPaths.outputDir, { recursive: true });

  const tempDir = createProjectTempDir(ROOT_DIR, "groove-fonts-");

  try {
    for (const plan of buildPlan.subsetPlans) {
      if (!plan.shouldBuild) {
        continue;
      }

      const outputPath = join(artifactPaths.outputDir, plan.outputFileName);
      runPyftsubset(plan.sourcePath, outputPath, plan.textValue, tempDir);
    }

    if (buildPlan.cssPlan.shouldWrite) {
      writeFileSync(artifactPaths.cssPath, buildPlan.cssPlan.text, "utf8");
    }

    removeStaleSubsetFiles(
      artifactPaths.outputDir,
      buildPlan.subsetPlans.map((plan) => plan.outputRelPath),
    );
    writeFileSync(artifactPaths.manifestPath, `${JSON.stringify(buildPlan.manifest, null, 2)}\n`, "utf8");
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

function logBuildStatus(result, logger, durationMs) {
  const durationText = formatDurationMs(durationMs);
  if (result.status === "cache-hit") {
    logger.log(`Font artifacts cache hit. (${durationText})`);
    return;
  }

  if (result.status === "rebuilt") {
    logger.log(`Font artifacts rebuilt: ${result.rebuiltSubsetCount}/${result.totalSubsetCount} subsets. (${durationText})`);
    return;
  }

  logger.log(`Font artifacts partially rebuilt: ${result.rebuiltSubsetCount}/${result.totalSubsetCount} subsets. (${durationText})`);
}

export function buildFontArtifacts({
  cacheRoot,
  reuseCache = true,
  logger = console,
  mode = "auto",
} = {}) {
  const startedAt = Date.now();
  const resolvedMode = resolveFontBuildMode(mode);
  ensureSourcesExist();

  const resolvedCacheRoot = cacheRoot
    ? cacheRoot
    : resolveSafeBuildSubdir(ROOT_DIR, DEFAULT_CACHE_ROOT, "--cache-root").resolvedPath;
  const artifactPaths = getFontArtifactPaths(resolvedCacheRoot);

  if (resolvedMode === "dev") {
    const devArtifactPaths = {
      ...artifactPaths,
      cssPath: join(artifactPaths.artifactRoot, "fonts.dev.css"),
    };
    mkdirSync(devArtifactPaths.artifactRoot, { recursive: true });
    writeFileSync(devArtifactPaths.cssPath, buildDevelopmentFontCssText(), "utf8");
    const durationMs = Date.now() - startedAt;
    logger.log(`Font source assets ready (dev mode). (${formatDurationMs(durationMs)})`);

    return {
      mode: resolvedMode,
      status: "dev",
      rebuiltSubsetCount: 0,
      totalSubsetCount: 0,
      durationMs,
      artifactPaths: devArtifactPaths,
      sourceAssetDescriptors: getDevelopmentFontAssetDescriptors(),
    };
  }

  ensureBuildToolsExist();
  const previousManifest = loadPreviousManifest(artifactPaths.manifestPath);
  const existingCssFingerprint = existsSync(artifactPaths.cssPath)
    ? computeContentHash(readFileSync(artifactPaths.cssPath, "utf8"))
    : null;
  const siteCorpusText = collectCorpusText();
  const poemCorpusText = collectPoemCorpusText();
  const sourceFingerprints = collectSourceFingerprints();
  const subsetDescriptors = buildSubsetDescriptors(sourceFingerprints, siteCorpusText, poemCorpusText);
  const cssText = buildFontCssText();

  const buildPlan = planFontArtifactBuild({
    subsetDescriptors,
    previousManifest,
    artifactExists: (outputRelPath) => existsSync(join(artifactPaths.artifactRoot, outputRelPath)),
    reuseCache,
    sourceFingerprints,
    corpusHashes: {
      site: computeContentHash(siteCorpusText),
      poem: computeContentHash(poemCorpusText),
    },
    cssText,
    existingCssFingerprint,
  });

  syncFontArtifacts(buildPlan, artifactPaths);
  const durationMs = Date.now() - startedAt;
  logBuildStatus(buildPlan, logger, durationMs);

  return {
    mode: resolvedMode,
    status: buildPlan.status,
    rebuiltSubsetCount: buildPlan.rebuiltSubsetCount,
    totalSubsetCount: buildPlan.totalSubsetCount,
    durationMs,
    artifactPaths,
    sourceAssetDescriptors: [],
  };
}

function parseCliArgs() {
  const args = process.argv.slice(2);
  let cacheRoot = DEFAULT_CACHE_ROOT;
  let force = false;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === "--cache-root") {
      cacheRoot = args[index + 1] || DEFAULT_CACHE_ROOT;
      index += 1;
      continue;
    }

    if (arg === "--force") {
      force = true;
    }
  }

  return { cacheRoot, force };
}

function main() {
  const options = parseCliArgs();
  const resolvedCacheRoot = resolveSafeBuildSubdir(ROOT_DIR, options.cacheRoot, "--cache-root").resolvedPath;
  buildFontArtifacts({
    cacheRoot: resolvedCacheRoot,
    reuseCache: !options.force,
  });
}

const isDirectRun = process.argv[1] != null && fileURLToPath(import.meta.url) === process.argv[1];

if (isDirectRun) {
  main();
}
