import { getDevelopmentFontAssetDescriptors } from '../catalog/development-assets.mjs';
import {
  BASIC_UNICODE_RANGE,
  FONT_FILES_DIRNAME,
  FONT_SPECS,
  NON_BASIC_UNICODE_RANGE,
  POEM_FONT_FAMILY_NAME,
} from '../catalog/specs.mjs';

const CONTENT_FONT_DISPLAY = 'block';

function appendPoemFontAliasCss(lines, { basicSrc, basicBoldSrc, nonBasicSrc }) {
  const poemWeights = [
    { weight: 400, serifSrc: basicSrc },
    { weight: 700, serifSrc: basicBoldSrc },
  ];

  for (const entry of poemWeights) {
    lines.push('@font-face {');
    lines.push(`  font-family: "${POEM_FONT_FAMILY_NAME}";`);
    lines.push(`  src: ${entry.serifSrc};`);
    lines.push('  font-style: normal;');
    lines.push(`  font-weight: ${entry.weight};`);
    lines.push(`  font-display: ${CONTENT_FONT_DISPLAY};`);
    lines.push(`  unicode-range: ${BASIC_UNICODE_RANGE};`);
    lines.push('}');
    lines.push('');
  }

  for (const weight of [400, 700]) {
    lines.push('@font-face {');
    lines.push(`  font-family: "${POEM_FONT_FAMILY_NAME}";`);
    lines.push(`  src: ${nonBasicSrc};`);
    lines.push('  font-style: normal;');
    lines.push(`  font-weight: ${weight};`);
    lines.push(`  font-display: ${CONTENT_FONT_DISPLAY};`);
    lines.push(`  unicode-range: ${NON_BASIC_UNICODE_RANGE};`);
    lines.push('}');
    lines.push('');
  }
}

export function buildDevelopmentFontCssText() {
  const lines = ['/* Generated by development font builder. */', ''];

  for (const descriptor of getDevelopmentFontAssetDescriptors()) {
    lines.push('@font-face {');
    lines.push(`  font-family: "${descriptor.familyName}";`);
    lines.push(`  src: url("/assets/fonts/${descriptor.fileName}") format("${descriptor.format}");`);
    lines.push('  font-style: normal;');
    lines.push(`  font-weight: ${descriptor.weight};`);
    lines.push(`  font-display: ${CONTENT_FONT_DISPLAY};`);
    lines.push('}');
    lines.push('');
  }

  appendPoemFontAliasCss(lines, {
    basicSrc: `url("/assets/fonts/NotoSerifCJKsc-Regular.otf") format("opentype")`,
    basicBoldSrc: `url("/assets/fonts/NotoSerifCJKsc-Bold.otf") format("opentype")`,
    nonBasicSrc:
      `url("/assets/fonts/Kaiti.ttf") format("truetype"), local("KaiTi"), local("Kaiti SC"), ` +
      `local("STKaiti"), local("Kai"), local("LXGW WenKai")`,
  });

  return `${lines.join('\n').trim()}\n`;
}

export function buildFontCssText() {
  const lines = ['/* Generated by font artifact builder. */', ''];

  for (const spec of FONT_SPECS) {
    for (const weight of Object.keys(spec.source)) {
      const subsets = [
        { suffix: 'basic', unicodeRange: BASIC_UNICODE_RANGE },
        { suffix: 'non-basic', unicodeRange: NON_BASIC_UNICODE_RANGE },
      ];

      for (const subset of subsets) {
        const fileName = `${spec.slug}-${subset.suffix}-${weight}.woff2`;
        lines.push('@font-face {');
        lines.push(`  font-family: "${spec.familyName}";`);
        lines.push(`  src: url("/assets/${FONT_FILES_DIRNAME}/${fileName}") format("woff2");`);
        lines.push('  font-style: normal;');
        lines.push(`  font-weight: ${weight};`);
        lines.push(`  font-display: ${CONTENT_FONT_DISPLAY};`);
        lines.push(`  unicode-range: ${subset.unicodeRange};`);
        lines.push('}');
        lines.push('');
      }
    }
  }

  appendPoemFontAliasCss(lines, {
    basicSrc: `url("/assets/${FONT_FILES_DIRNAME}/noto-serif-sc-basic-400.woff2") format("woff2")`,
    basicBoldSrc: `url("/assets/${FONT_FILES_DIRNAME}/noto-serif-sc-basic-700.woff2") format("woff2")`,
    nonBasicSrc:
      `url("/assets/${FONT_FILES_DIRNAME}/site-kai-non-basic-400.woff2") format("woff2"), local("KaiTi"), ` +
      `local("Kaiti SC"), local("STKaiti"), local("Kai"), local("LXGW WenKai")`,
  });

  return `${lines.join('\n').trim()}\n`;
}
